### ISSUE TITLE
insightcae Windows Installation Error

### ISSUE THREAD

**Issue by VijayN10** [hkroeger/insightcae#33]
Dear Team,

Thank you for developing opensource GUI based software. 

I have installed insightcae as per the instructions given on the website. The X-server is also running. But after installation, when I open workbench from my windows menu, it is opening ubuntu 18.04 and closing immediately. I am not sure where did I go wrong. Could you please guide me on this?

Thank you.

**Comment by hkroeger** [comment]
Dear Vijay,

thanks for your feedback!

The installation instructions on the website are outdated. We have given up the path to run the GUI tools from within WSL due to several shortcomings especially concerning hardware accelerated graphics and the VTK toolkit.

The current path is to cross-compile all the GUI tools natively for Windows and execute the backend tools (OpenFOAM, Code_Aster and so on) in a WSL environment in a client-server manner.

The installation for this is described here in the section "Obtaining InsightCAE": 
https://raw.githubusercontent.com/hkroeger/insightcae-documentation/master/insightcae-manual.pdf

Regards, Hannes

**Comment by VijayN10** [comment]
Dear Hannes,

Thank you so much for your response. I will check the installation guideline and update you soon.

**Comment by VijayN10** [comment]
Dear Hannes,

Sorry for the late reply. I am able to install the software with the help of a pdf shared by you. 
Many Thanks!

**Comment by jiayxxh** [comment]
Hi, could you please share the steps to install the insight cae on win10 system😀 thank you.

**Comment by hkroeger** [comment]
Hi!
The install steps are as outlined in the manual linked above:
* Download the installer from the web server
* Execute and follow the steps.
I have to note that there seems to be a problem with the installation of the WSL image. We are currently in the process of debugging the installer.
