### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by sfakhim** [hkroeger/insightcae#5]
I am trying to install Insight CAE. I am getting following error: 
CMake Error at CMake/FindOpenFOAM-esi1806.cmake:36 (string):
   string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
   command.
when I am searching in CMakeLists. txt there is no REGEX in code!! How Can I solve the problem?
Thank you,

**Comment by hkroeger** [comment]
Dear sfakim,
I have seen this error with older versions of CMake.
Currently, I'm using version 3.10.2. I have some systems, where CMake 3.5 is installed.
Which CMake version do you use?
Regards, Hannes

**Comment by sfakhim** [comment]
Hello Hannes, 
I have installed latest version of CMake which is 3.12.1.

**Comment by hkroeger** [comment]
The error message is a bit unspecific unfortunately and many reasons are possible.
I just came across one possibility: cmake shall search for  the "bashrc" of different possible OpenFOAM installations. Sometimes it picks up the wrong one and this error is emitted because the scripts return garbage and this garbage is passed to REGEX.
You might check the CMakeCache.txt Search for "_BASHRC" and check whether there are sensible values detected for all entries (especially they should contain "OF*_BASHRC-NOTFOUND", if the OpenFOAM version under consideration is not present.
