### ISSUE TITLE
uploading geometry file

### ISSUE THREAD

**Issue by ofrikutchinsky** [hkroeger/insightcae#9]
hi !
tried to upload an stl file to snappyHexMesh. it worked before, now this error pops up
![image](https://user-images.githubusercontent.com/54778416/64860344-8c7b1c80-d635-11e9-9c17-c07fbb3755f7.png)
help please :(
thank you ! ofri

**Comment by hkroeger** [comment]
Hi ofri,
From what I can spot in picture, it looks like the "Value" field contains something in quotes. There should be no quotes...

By the way, the rule for opening is:
* extension "stl" or "stlb": open with paraview
* extension "stp", "step", "igs", "iges", "iscad", "brep": open with iscad
* everything else is tried to open using QDesktopServices.
The latter failed obviously here. Thus the other extensions were not recognized. I guess because of a malformed file name string.

Did you select the file using the "..." button?
Does the file path contain spaces?
